language: go
sudo: false
os: linux

go:
  - 1.8.x
  - 1.9.x
  - tip

jobs:
  include:
    - stage: test
      script:
        - make test
    - stage: test
      install:
        - go get -u github.com/gordonklaus/ineffassign
      script:
        - make test-long
        - make ineffassign
