jobs:
  include:
    - stage: test
      language: go
      go: 1.12.x
      script:
        - make
        - make test
    - stage: test
      language: go
      go: 1.13.x
      script:
        - make
        - make test
    - stage: test
      language: go
      go: 1.12.x
      install:
        - go get -u github.com/gordonklaus/ineffassign
      script:
        - make test-long
        - make ineffassign
    - stage: test
      language: go
      go: 1.13.x
      install:
        - go get -u github.com/gordonklaus/ineffassign
      script:
        - make test-long
        - make ineffassign
    - stage: test
      language: go
      go: 1.13.x
      script:
        - go build -o /dev/null ./doc/examples/offline_transaction
    - stage: test
      language: go
      go: 1.13.x
      script:
        - make install-std
        - cd examples/rivchain
        - bash generate.sh
        - bash modcheck.sh
        - make install-std
