jobs:
  include:
    - stage: test
      language: go
      go: 1.12.x
      script:
        - make
        - make test
    - stage: test
      language: go
      go: 1.13.x
      script:
        - make
        - make test
    - stage: test
      language: go
      go: 1.12.x
      install:
        - go get -u github.com/gordonklaus/ineffassign
        - go get -u honnef.co/go/tools/cmd/staticcheck
      script:
        - make test-long PARALLEL=4
        - make ineffassign
        - make staticcheck
    - stage: test
      language: go
      go: 1.13.x
      install:
        - go get -u github.com/gordonklaus/ineffassign
        - go get -u honnef.co/go/tools/cmd/staticcheck
      script:
        - make test-long PARALLEL=4
        - make ineffassign
        - make staticcheck
    - stage: test
      language: go
      go: 1.13.x
      script:
        - go build -o /dev/null ./doc/examples/offline_transaction
    - stage: test
      language: go
      go: 1.13.x
      install:
        - go get -u golang.org/x/tools/cmd/goimports
      script:
        - make install-std
        - cd examples/rivchain
        - bash generate.sh
        - bash modcheck.sh
        - make install-std
