
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"


[[constraint]]
  name = "github.com/NebulousLabs/bolt"
  version = "1.0.0-255-gdfb2120"

[[constraint]]
  branch = "master"
  name = "github.com/NebulousLabs/demotemutex"

[[constraint]]
  branch = "master"
  name = "github.com/NebulousLabs/ed25519"

[[constraint]]
  branch = "master"
  name = "github.com/bgentry/speakeasy"

[[constraint]]
  branch = "master"
  name = "github.com/inconshreveable/go-update"

[[constraint]]
  name = "github.com/julienschmidt/httprouter"
  version = "1.1.0-29-g77366a4"
